### ISSUE TITLE
Ubuntu compatibility issues 

### ISSUE THREAD

**Issue by nguzman313** [DuncanLab/OpenMaze#100] opened 2020-09-02 21:02 UTC
Hi guys,

Sorry to take up your time with what is likely a trivial issue, but I have been unable to resolve it on my own as I am relatively new to Unity. When launching the tutorial experiments (i.e. pressing play button, selecting proper configuration file), the experiment does not advance past the first trial with the Launch Experiment scene after I press the `Start Experiment` button (OpenMaze 1.0.1) or press the spacebar (OpenMaze 1.0.0). I have tried this process in both OpenMaze 1.0.0 and 1.0.1 with the same result. The only messages that appear in the console in both versions are

`Creating new Instructional Trial`
`UnityEngine.Debug:Log(Object)`

and

`Creating new 3D Screen Trial`
`UnityEngine.Debug:Log(Object)`

The full message in the console log is of the form

`Creating new Instructional Trial`
`UnityEngine.Debug:Log(Object)`
`trial.FieldTrial:GenerateTrials() (at Assets/Scripts/trial/FieldTrial.cs:67)`
`trial.FieldTrial:Update(Single) (at Assets/Scripts/trial/FieldTrial.cs:123)`
`main.Loader:Update() (at Assets/Scripts/main/Loader.cs:51)`

with the number following `FieldTrial.cs:` in the first path after `GenerateTrials()` differing from `67` depending on the trial being constructed. I have not been able to find anything in the build settings, configuration files, or C# scripts that would be a likely culprit. It could be just a fluke with the tutorial experiments, but I'd like to get it resolved in the tutorials before moving on to my own projects in case the issue persists there.

I'm running `Ubuntu 18.04.4` on an HP machine. For OpenMaze 1.0.0, the Unity version is `2019.2.19f1` and for OpenMaze 1.0.1, the Unity version is `2019.4.4f1`. Thank you for your time.

Best,

Noah Guzman

**Comment by hongyu-wang** [comment] 2020-09-09 05:39
Hey, could you please send the configuration file you used. Thanks!

**Comment by nguzman313** [comment] 2020-09-09 17:47
I tried the first three tutorial experiments in both versions of OpenMaze and got the same results for all three. Here are the configuration files:

[OpenMaze_Config_Files_For_Bug.zip](https://github.com/DuncanLab/OpenMaze/files/5197047/OpenMaze_Config_Files_For_Bug.zip)

**Comment by hongyu-wang** [comment] 2020-09-09 21:14
Hey, so could you also include a screen capture and also include the log file for when you try to run the experiment. You can see more information about the log files here:
https://docs.unity3d.com/Manual/LogFiles.html

**Comment by SilicoBen** [comment] 2020-09-09 22:47
Just to confirm, are you using the most recent release of the software V1.1.0?

**Comment by nguzman313** [comment] 2020-09-10 00:59
I am not using V1.1.0. I have attempted with both V1.0.1 and V1.0.0, getting the same results with both. I am happy to attempt using V1.1.0. 

Here are screencasts for my attempts to run the experiments for Tutorials 1 and 2 in V1.0.1 as well as the portion of the Editor log file associated with each run:

[Screencasts_Editor_Log.zip](https://github.com/DuncanLab/OpenMaze/files/5198548/Screencasts_Editor_Log.zip)

I will clone the V1.1.0 repo and try again.

**Comment by SilicoBen** [comment] 2020-09-10 02:45
Yes, please use V1.1.0. I have just downloaded and retested the tutorials to ensure that they are working correctly. Make sure that you add the Tutorial Environments Scenes to the build before trying to launch the configuration files (This process is demonstrated in the tutorial videos). Please let me know how it works out!

**Comment by nguzman313** [comment] 2020-09-10 19:34
Unfortunately the issue persists in V1.1.0. Here is a screenshot of my Build Settings window as well as the relevant portion of the Editor log file for when I attempt to run the first tutorial experiment (config file `Tutorial 1 - Test OpenMaze.json`)  with V1.1.0:

[Build_Settings_and_Editor_Log.zip](https://github.com/DuncanLab/OpenMaze/files/5204217/Build_Settings_and_Editor_Log.zip)

Looking through the Editor logs in all versions of OpenMaze that I have tried (including V1.1.0), the common problem appears to be that upon hitting the play button, Unity looks for a CSV file in the `OuputFiles` directory and cannot find the file. The name of the file it looks for is a date-time string with the date and time at which the play button was pressed. My guess is that some script is supposed to create this file at the start of play and is failing to do so.

**Comment by SilicoBen** [comment] 2020-09-10 20:12
Strange, since I cannot replicate this issue on my mac or windows machines, and knowing that the issue likely has something to do with the output files I have a few things you could try. 

1. Try entering something into each of the starfields before pressing play - I'm fairly certain this is not the cause, but may as well give it a shot.

2. Check program permissions - Upon launching your first experiment, an output folder should be generated automatically in the assets folder (OpenMazeV1.1.0/Assets/Outputfiles~. Subsequently, each time you run an experiment a new .csv file is automatically generated, in this folder. it could be the case that Unity doesn't have permission to create these files. 

3. It could have something to do with Ubuntu and the data output scripts. I did a quick bit of googling and I think it might be an issue with the System DateTime.Now function or perhaps the writer.write function as it appears there are some differences across platforms. The two scripts that handle OpenMaze output are Loader.cs (Scripts\main\Loader.cs) -  and, at the very start of the experiment, FieldTrial.cs (Scripts\trial\FieldTrial.cs) which creates the file name.

Let me know if you have any luck with this. I'm also happy to set up a video/screen share call with you to help troubleshoot things if this doesn't help. Feel free to shoot me an email anytime as well - k.b.nealy@gmail.com. I'm certain that we'll be able to figure this out and get you up and running.

**Comment by nguzman313** [comment] 2020-09-11 00:58
Ok so it looks like Ubuntu's file system isn't playing nice with C#. The `StreamWriter` was writing the `OutputFiles~` directory with a lowercase `f` as `Outputfiles~`. This caused trouble since the `Loader` script was looking for a capital `F`. I'm not sure why this happens, since the directory name in the `StreamWriter` object is `OutputFiles~`, not `Outputfiles~`. Manually renaming the directory fixed this and allowed the first experiment to advance to Trial 1, the Welcome Page. Things went wrong again, as the experiment did not advance past this and the Welcome Page image did not show up, and the console log gave me these messages:

`Goal object not set: running an instructional trial`
`UnityEngine.Debug:LogWarning(Object)`
`wallSystem.PlayerController:Start() (at Assets/Scripts/wallSystem/PlayerController.cs:64)`

`Can't set controller object: running an instructional trial`
`UnityEngine.Debug:LogWarning(Object)`
`wallSystem.PlayerController:Start() (at Assets/Scripts/wallSystem/PlayerController.cs:94)`

and then an endless loop of this message:

`Skipping movement calc: instructional trial`
`UnityEngine.Debug:LogWarning(Object)`
`wallSystem.PlayerController:Update() (at Assets/Scripts/wallSystem/PlayerController.cs:256)`

The log file wasn't any more informative about these messages, but I checked the `cs` scripts indicated (`PlayerController.cs`) and the first message indicates a null reference error. Turns out the config file for the first tutorial experiment gives the image names with lowercase `.png` file extensions, but in the `2D_Objects` directory, many of the images have uppercase `.PNG` file extensions, and I guess C# is sensitive to case in file extensions so this throws a null reference error. Manually renaming the images to have the lowercase extension partially worked: the experiment advanced to the first trial and the Welcome Page image was displayed. But I am unable to get the experiment to advance to the next trial, the Task Instructions page. As soon as the experiment advances to the first trial and the Welcome Page image is displayed, I just get those same first three console log messages again. I'm sure it's something similar to the situations above, so I will keep working to figure it out and let you know if I resolve it.

**Comment by SilicoBen** [comment] 2020-09-11 12:43
Thanks for the update. very strange about the case sensitivity but glad you could make some progress on this. I'm thinking that we could probably slap some code to change everything to lower in the C#. I believe @codyhowarth might be able to help you out with the ubuntu stuff.   

Also, the endless loop of "skipping movement calc" is actually expected behaviour.  To clarify, on the start screen did you press space to continue on to the next trial? Also, did you make sure to add the tutorial environments to the build? they should occupy Scene # 4,5 in order for the configuration files to execute properly. You can add these scenes by first opening them in the editor and then navigating to **File->Build Settings** and then clicking add open scenes. 

Please keep us updated on any progress you make as we would like to patch current version with your fix. Thanks for your patience and working with us to solve this issue!

**Comment by codyhowarth** [comment] 2020-09-13 04:03
@nguzman313, You are correct that renaming the .png files to lower case should fix that particular issue. I would suggest doing a search within the `Assets` directory to be certain all files are changed. 

The reason you can't advance from the first screen is due to a bug in the Linux version of the Unity editor. Apparently, the space key is not recognized properly on Linux (I believe building the project would work correctly). For now, I would recommend replacing any instances of `"TrialEndKey": "Space"` within the .json files with another key e.g. `"TrialEndKey": "x" `.

As @kbnealy suggests, we will look to patch these issues in a future version.

**Comment by SilicoBen** [comment] 2020-09-16 10:59
@codyhowarth thanks for the important insight about the space key issue. @nguzman313 let us know if this worked for you and I'll go ahead and close the issue and add some notes to our current release.

**Comment by nguzman313** [comment] 2020-09-19 07:03
Sorry for the delay in getting back to you guys. Changing the trial end key as suggested by @codyhowarth works perfectly. I am able to advance the trials with no issue now. Thanks for your patience in resolving this, I appreciate your time.

**Comment by SilicoBen** [comment] 2020-09-19 10:37
@nguzman313 that's great news! Glad we could help. I'll these notes to the release. Please feel free to reach out if you encounter any other issues.

**Closed as completed by SilicoBen** 2020-09-19 10:37 UTC
Labels: bug
