### ISSUE TITLE
Output for instruction trials

### ISSUE THREAD

**Issue by SilicoBen** [DuncanLab/OpenMaze#58] opened 2019-11-22 15:14 UTC
It doesn't seem that the output for instructions is working? Maybe this is another branch?

**Comment by SilicoBen** [comment] 2019-11-24 16:58
I'm fairly certain that this was addressed in a previous branch because i was using it when doing the timing analysis. Not sure what happened. This would be very helpful for the first release.

**Comment by codyhowarth** [comment] 2020-01-05 22:52
Duplicate of #36

**Closed as completed** 2020-01-25 21:50 UTC
Labels: duplicate
